apiVersion: v1
kind: ReplicationController
metadata:
  name: collection
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: collection
    spec:
      containers:
      - name: collection
        image: weaveworks/scope:f68fa077f6b2
        args:
        - --no-probe
        - --app.log.http=true
        - --app.weave.addr=
        - --app.http.address=:80
        - --app.userid.header=X-Scope-OrgID
        - --app.collector=dynamodb://AKIAJFWTRBJFTLBFXTAA:XZDGOZhMIEhuL0GQlKzBe5bkEpQPEbosOPePAa8Q@us-east-1/dev_reports
        env:
        - name: CHECKPOINT_DISABLE
          value: "1"
        - name: SCOPE_HOSTNAME
          value: "service"
        ports:
        - containerPort: 80
