apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend-f5d1f69
spec:
  replicas: 2
  selector:
    name: frontend
    version: f5d1f69
  template:
    metadata:
      labels:
        name: frontend
        version: f5d1f69
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name: frontend
        image: quay.io/weaveworks/frontend:f5d1f69
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: tls-secret
          mountPath: /tls/secret/
          readOnly: true
      volumes:
      - name: tls-secret
        secret:
          secretName: tls-secret
