apiVersion: v1
kind: ReplicationController
metadata:
  name: metrics-98d4fd7
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: metrics-98d4fd7
        version: 98d4fd7
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name: metrics
        image: quay.io/weaveworks/metrics:98d4fd7
        args:
        - -database-uri=postgres://postgres:29fcf745896ac1f83c15ea03a22afcc2e4851048@users-database-devx.cps0r5emv3nc.us-east-1.rds.amazonaws.com/users?sslmode=disable
        - -endpoint=https://bi.weave.works/import/service_dev/users
