apiVersion: v1
kind: ReplicationController
metadata:
  name: users
  labels:
    name: users
spec:
  replicas: 1
  selector:
    name: users
  template:
    metadata:
      labels:
        name: users
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name: users
        image: quay.io/weaveworks/users:8b7f1d8
        args:
        - -session-secret=3919365780a79e0658fd44d03e6945a080031ec077b88975898f698c0d298395
        - -email-uri=smtp://AKIAJC77KJCIV4HRCM2Q:AqliFmKAFLPagTQkd6FuoZHQDolVU195DorateSEKsTO@email-smtp.us-east-1.amazonaws.com:587
        - -database-uri=postgres://postgres:us45dcd40163798d@users-database.cps0r5emv3nc.us-east-1.rds.amazonaws.com/users?sslmode=disable
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
