apiVersion: v1
kind: ReplicationController
metadata:
  name: users-cb08840
spec:
  replicas: 2
  selector:
    name: users
    version: cb08840
  template:
    metadata:
      labels:
        name: users
        version: cb08840
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name: users
        image: quay.io/weaveworks/users:cb08840
        args:
        - -domain=http://frontend.dev.weave.works
        - -session-secret=56ee20ee7e8dc0b366abb1df4b3ac22ae05566d8eb18cba26f1c0925b1b9c7bf
        - -sendgrid-api-key=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
        - -database-uri=postgres://postgres:29fcf745896ac1f83c15ea03a22afcc2e4851048@users-database-devc.czc9e0lwsult.eu-west-1.rds.amazonaws.com:/users?sslmode=disable
        - -pardot-email=tom@weave.works
        - -pardot-password=Zi23R}aV7T
        - -pardot-userkey=94f4347b4f6e55ff9b2057fcae67056e
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
