[[constraint]]
  branch = "expose-dstaddr"
  name = "github.com/armon/go-proxyproto"
  source = "github.com/weaveworks/go-proxyproto"

# google/go-github have added contexts to their API.  Pin version until we
# can update.
[[constraint]]
  name = "github.com/google/go-github"
  revision = "a8b8751f9d056ab7f60ab6d9caba15db9d701b09"

# github.com/opentracing-contrib/go-stdlib doesn't support hijacking until
# https://github.com/opentracing-contrib/go-stdlib/pull/11 is merged.
[[constraint]]
  name = "github.com/opentracing-contrib/go-stdlib"
  source = "github.com/weaveworks/go-stdlib"
  branch = "hijack"

[[constraint]]
  name = "github.com/justinas/nosurf"
  revision = "cbe5fdb4a426586632a1ff60eca311bd286220f5"
