# Specifying 'required = ["codec/codecgen"]' is needed in order to pull the
# necessary sources to generate code used by billing-synthetic-usage-injector.
# Otherwise, building fails with:
#   make: *** No rule to make target `vendor/github.com/weaveworks/scope/report/report.codecgen.go'.  Stop.
required = ["github.com/ugorji/go/codec/codecgen"]

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  # gcp-service depends on the `gogo.proto` file shipped in the subpackage
  # github.com/gogo/protobuf/gogoproto, so we must not prune non-go files.
  [[prune.project]]
    name = "github.com/gogo/protobuf"
    non-go = false

[[constraint]]
  branch = "expose-dstaddr"
  name = "github.com/armon/go-proxyproto"
  source = "github.com/weaveworks/go-proxyproto"

# google/go-github have added contexts to their API.  Pin version until we
# can update.
[[override]]
  name = "github.com/google/go-github"
  revision = "59aa6eea1c58ba063a0c3b90a16499cb39e6332a"

# github.com/opentracing-contrib/go-stdlib doesn't support hijacking until
# https://github.com/opentracing-contrib/go-stdlib/pull/11 is merged.
[[constraint]]
  name = "github.com/opentracing-contrib/go-stdlib"
  source = "github.com/weaveworks/go-stdlib"
  branch = "hijack"

[[constraint]]
  name = "github.com/justinas/nosurf"
  revision = "cbe5fdb4a426586632a1ff60eca311bd286220f5"

# Override until https://github.com/FrenchBen/goketo/pull/14 is merged
[[constraint]]
  name = "github.com/FrenchBen/goketo"
  source = "github.com/weaveworks/goketo"
  branch = "sirupsen-case"

# Pin to master flux instead of a specific release so that we can develop
# flux-api for against it.
[[constraint]]
  name = "github.com/weaveworks/flux"
  branch = "master"

# Stackdriver logging with notifications; no logs are shown on the cloud logging console
# when using last release (on Dec 11, 2017 v0.17.0 050b16d)
[[constraint]]
  name = "cloud.google.com/go"
  revision = "eb1cc5f3c0a93e56aa3c13e3ad4f336d327c0c86"

# Pin to master branch until there is a more recent stable release:
#   https://github.com/prometheus/client_golang/issues/375
# Has to be an override rather than a constraint otherwise jaeger-lib wins
[[override]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/weaveworks/billing-client"

# Force common to latest commit otherwise dep picks one from 8 months ago
[[constraint]]
  name = "github.com/weaveworks/common"
  revision = "2a0cb6145a2f541de5ca19437fee675baf6a1985"
