# By default, dep pulls both gopkg.in/mattes/migrate and github.com/mattes/migrate,
# which breaks the build following dep ensure:
# We therefore ignore github.com/mattes/migrate to avoid conflicts:
ignored = ["github.com/mattes/migrate"]

# By default, dep pulls both gopkg.in/mattes/migrate and github.com/mattes/migrate,
# which breaks the build following dep ensure:
# We therefore enforce v1.3.2 via gopkg.in to avoid conflicts:
[[override]]
  name = "gopkg.in/mattes/migrate.v1"
  version = "v1.3.2"

[[constraint]]
  branch = "expose-dstaddr"
  name = "github.com/armon/go-proxyproto"
  source = "github.com/weaveworks/go-proxyproto"

# google/go-github have added contexts to their API.  Pin version until we
# can update.
[[override]]
  name = "github.com/google/go-github"
  revision = "59aa6eea1c58ba063a0c3b90a16499cb39e6332a"

# github.com/opentracing-contrib/go-stdlib doesn't support hijacking until
# https://github.com/opentracing-contrib/go-stdlib/pull/11 is merged.
[[constraint]]
  name = "github.com/opentracing-contrib/go-stdlib"
  source = "github.com/weaveworks/go-stdlib"
  branch = "hijack"

[[constraint]]
  name = "github.com/justinas/nosurf"
  revision = "cbe5fdb4a426586632a1ff60eca311bd286220f5"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.0.0"

# Override until https://github.com/FrenchBen/goketo/pull/14 is merged
[[constraint]]
  name = "github.com/FrenchBen/goketo"
  source = "github.com/weaveworks/goketo"
  branch = "sirupsen-case"

# Pin to master flux instead of a specific release so that we can develop
# flux-api for against it.
[[constraint]]
  name = "github.com/weaveworks/flux"
  branch = "master"
