ALTER TABLE notebooks
    ALTER COLUMN org_id SET NOT NULL,
    ALTER COLUMN created_by SET NOT NULL,
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN updated_by SET NOT NULL,
    ALTER COLUMN updated_at SET NOT NULL,
    ALTER COLUMN title SET NOT NULL;
