apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    prometheus.io.port: "9145"
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    name: frontend
  type: LoadBalancer
