apiVersion: v1
kind: ReplicationController
metadata:
  name: users-master-4f69380
spec:
  replicas: 2
  selector:
    name: users
    version: master-4f69380
  template:
    metadata:
      labels:
        name: users
        version: master-4f69380
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name: users
        image: quay.io/weaveworks/users:master-4f69380
        args:
        - -domain=https://cloud.weave.works
        - -session-secret=3919365780a79e0658fd44d03e6945a080031ec077b88975898f698c0d298395
        - -sendgrid-api-key=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
        - -database-uri=postgres://postgres:usvqvHmLw2EahFK9Pa@users-database.cqqzyyx2xnct.us-east-1.rds.amazonaws.com/users?sslmode=disable
        - -database-migrations=/migrations
        - -pardot-email=tom@weave.works
        - -pardot-password=Zi23R}aV7T
        - -pardot-userkey=94f4347b4f6e55ff9b2057fcae67056e
        - -github-client-id=572566d27541a438dbec
        - -github-client-secret=9cb158d2e82f70022ae485106e6ac387dae852b2
        - -github-redirect-url=https://cloud.weave.works/login-via/github
        # Google OAuth client lives in the weaveworks (hallowed-hold-777) project
        - -google-client-id=351720542146-h3l2d7te1o47fsjktlbthnnrlehsvj0f.apps.googleusercontent.com
        - -google-client-secret=qHF8c9CzbW7CmlaOsrdx9ry_
        - -google-redirect-url=https://cloud.weave.works/login-via/google
        ports:
        - containerPort: 80
