apiVersion: v1
kind: ReplicationController
metadata:
  namespace: monitoring
  name: grafana
spec:
  replicas: 1
  selector:
    name: grafana
  template:
    metadata:
      labels:
        name: grafana
    spec:
      containers:
      - name: grafana
        image: quay.io/weaveworks/grafana
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      - name: gfdatasource
        image: quay.io/weaveworks/gfdatasource
        imagePullPolicy: IfNotPresent
