apiVersion: v1
kind: ReplicationController
metadata:
  name: metrics
  namespace: monitoring
spec:
  replicas: 1
  selector:
    name: metrics
  template:
    metadata:
      labels:
        name: metrics
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name: metrics
        image: quay.io/weaveworks/metrics
        imagePullPolicy: IfNotPresent
        args:
        - -database-uri=postgres://postgres@users-db.aws.svc.cluster.local/users?sslmode=disable
        - -endpoint=https://bi.weave.works/import/service_dev/users
