apiVersion: v1
kind: ReplicationController
metadata:
  name: control-master-4fa40e2
spec:
  replicas: 2
  selector:
    name: control
    version: master-4fa40e2
  template:
    metadata:
      labels:
        name: control
        version: master-4fa40e2
    spec:
      containers:
      - name: control
        image: weaveworks/scope:master-4fa40e2
        args:
        - --no-probe
        - --weave=false
        - --app.log.http=true
        - --app.http.address=:80
        - --app.userid.header=X-Scope-OrgID
        - --app.control.router=sqs://AKIAJECDWWRQWFNHFO2A:dP12kF6wREosllk%2B3%2B3ZqPpZxeDlGn%2FYgKebMJVj@us-east-1/dev_control_
        env:
        - name: CHECKPOINT_DISABLE
          value: "1"
        - name: SCOPE_HOSTNAME
          value: "service"
        ports:
        - containerPort: 80
