apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    prometheus.io.port: "9145"
spec:
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    name: frontend
  type: LoadBalancer
