apiVersion: v1
kind: ReplicationController
metadata:
  name: launch-generator-471989f
spec:
  replicas: 2
  selector:
    name: launch-generator
    version: 471989f
  template:
    metadata:
      labels:
        name: launch-generator
        version: 471989f
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name: launch-generator
        image: quay.io/weaveworks/launch-generator:471989f
        ports:
        - containerPort: 8080
