apiVersion: v1
kind: Service
metadata:
  name: nats
  annotations:
    prometheus.io.port: "9148"
spec:
  ports:
  - name: clients
    port: 4222
  - name: httpmonitoring
    port: 8222
  - name: cluster
    port: 6222
  - name: prom
    port: 9148
  selector:
    name: nats
