apiVersion: v1
kind: ReplicationController
metadata:
  name: query-master-4fa40e2
spec:
  replicas: 2
  selector:
    name: query
    version: master-4fa40e2
  template:
    metadata:
      labels:
        name: query
        version: master-4fa40e2
    spec:
      containers:
      - name: query
        image: weaveworks/scope:master-4fa40e2
        args:
        - --no-probe
        - --weave=false
        - --app.log.http=true
        - --app.http.address=:80
        - --app.userid.header=X-Scope-OrgID
        - --app.collector=dynamodb://AKIAJI4S2QEEF27QVJXQ:BixrkOgl%2Bu%2F2dfEJhdtItwsm8cMLNLPwDN%2BQt5Sr@us-east-1/dev_reports
        - --app.collector.s3=s3://AKIAJI4S2QEEF27QVJXQ:BixrkOgl%2Bu%2F2dfEJhdtItwsm8cMLNLPwDN%2BQt5Sr@us-east-1/weaveworks_dev_reports
        - --app.nats=nats://nats.default.svc.cluster.local:4222
        - --app.memcached.hostname=memcached.default.svc.cluster.local
        - --app.memcached.timeout=100ms
        - --app.memcached.service=memcached
        env:
        - name: CHECKPOINT_DISABLE
          value: "1"
        - name: SCOPE_HOSTNAME
          value: "service"
        ports:
        - containerPort: 80
