apiVersion: v1
kind: ReplicationController
metadata:
  name: ui-server-master-778ecbb
spec:
  replicas: 2
  selector:
    name: ui-server
    version: master-778ecbb
  template:
    metadata:
      labels:
        name: ui-server
        version: master-778ecbb
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name: ui-server
        image: quay.io/weaveworks/ui-server:master-778ecbb
        ports:
        - containerPort: 80
