#!/bin/bash -e

function usage {
    echo "usage: $(basename $0) <name> [...]" 1>&2
    exit 1
}


if [ ! $# -ge 1 ]
then
    usage
fi

ENV_NAME="$1"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ENV_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/$1"

MASTER="$(terraform output -module=kubernetes-anywhere-aws-ec2 -state="${ENV_DIR}/tfstate" kubernetes-master-ip)"


SSH_OPTS=(
  -o Compression=yes
  -o LogLevel=FATAL
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null
  -o IdentitiesOnly=yes
  -o ForwardAgent=yes
)

SSH_KEY="${ENV_DIR}/k8s_id_rsa"
chmod 0600 "${SSH_KEY}" # this is required because git only respects owner bits

ssh "${SSH_OPTS[@]}" -i "${SSH_KEY}" "ubuntu@${MASTER}" \
  kubernetes-anywhere-toolbox print-ec2-public-config
