#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

function usage {
	echo "usage: $(basename $0) <env> <user>" 1>&2
	exit 1
}


if [ $# -ne 2 ]
then
	usage
fi

ENV=$1
USER=$2
CLWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/${ENV}"

if [ ! -d ${CLWD} ]
then
	echo "${CLWD} is not a directory"
	exit 1
fi

id=$( cat ${CLWD}/tfstate | jq -r .modules[0].resources.\"aws_iam_access_key.${USER}_key\".primary.attributes.id )
secret=$( cat ${CLWD}/tfstate | jq -r .modules[0].resources.\"aws_iam_access_key.${USER}_key\".primary.attributes.secret )

echo "Access Key:                 ${id}"
echo "Access Secret:              ${secret}"
echo ""
echo "Access Key (urlencoded):    $(python -c "import urllib; print urllib.quote('''${id}''')")"
echo "Access Secret (urlencoded): $(python -c "import urllib; print urllib.quote('''${secret}''')")"
