#!/usr/bin/env bash

# This file is an adaptation of https://get.k8s.io.

set -o errexit
set -o nounset
set -o pipefail

if [ $# -ne 2 ]
then
	echo "usage: $(basename $0) up/down <name>"
	exit 1
fi

WHAT=$1
NAME=$2
VERSION="v1.1.1" # https://storage.googleapis.com/kubernetes-release/release/stable.txt

echo "Sourcing ${NAME}/var"
source ${NAME}/var

function export_variables {
	export KUBERNETES_PROVIDER="aws"
	export KUBE_AWS_ZONE="${K8S_AZ}"
	export AWS_S3_REGION="${AWS_REGION}"
	export AWS_S3_BUCKET="weaveworks-scope-kubernetes-$(date | shasum | cut -c 1-7)"
	export AWS_IMAGE="${K8S_AMI}"
	export MASTER_SIZE="${K8S_MASTER_SIZE}"
	export MINION_SIZE="${K8S_MINION_SIZE}"
	export NUM_MINIONS="${K8S_NUM_MINIONS}"
	export KUBE_AWS_INSTANCE_PREFIX="kubernetes_pb"
}

function ensure_release {
	if [ -d kubernetes ]
	then
		echo "Kubernetes directory already exists"
		return
	fi
	if [ ! -f kubernetes.tar.gz ]
	then
		echo "Downloading Kubernetes ${VERSION}"
		URL="https://storage.googleapis.com/kubernetes-release/release/${VERSION}/kubernetes.tar.gz"
		wget -q --show-progress ${URL}
	fi
	echo "Unpacking Kubernetes ${VERSION}"
	tar zxf kubernetes.tar.gz
	echo "Patching Kubernetes scripts"
	wget -q -O kubernetes/cluster/aws/config-default.sh https://raw.githubusercontent.com/peterbourgon/kubernetes/master/cluster/aws/config-default.sh
	wget -q -O kubernetes/cluster/aws/util.sh https://raw.githubusercontent.com/peterbourgon/kubernetes/master/cluster/aws/util.sh
}

function move_kubeconfig {
	if [ -f ${HOME}/.kube/config ]
	then
		TIMESTAMP=$(date +%Y%m%d%H%M%S)
		echo "Detected ${HOME}/.kube/config"
		echo "Moving it to ${HOME}/.kube/config.backup.${TIMESTAMP}"
		mv ${HOME}/.kube/config ${HOME}/.kube/config.backup.${TIMESTAMP}
	fi
}

function kube_up {
	(
		cd kubernetes
		./cluster/kube-up.sh
		echo "Kubernetes installation successful."
	)
}

function write_kubeconfig {
	echo "Writing ${NAME}.kubeconfig"
	cp ${HOME}/.kube/config ${NAME}.kubeconfig
}

function kube_down {
	(
		cd kubernetes
		./cluster/kube-down.sh
		echo "Kubernetes deinstallation successful."
	)
}

function remove_kubeconfig {
	echo "Removing ${NAME}/kubeconfig"
	rm -f ${NAME}/kubeconfig
}

function clean_s3_buckets {
	for b in $(aws s3 ls / | grep weaveworks-scope-kubernetes- | awk '{print $3}')
	do
		echo $b
		aws s3 rm --recursive s3://$b/ >/dev/null 2>&1 || true
		aws s3 rb s3://$b >/dev/null 2>&1 || true
	done
}

function interactive_confirmation {
	while true
	do
		read -p "$1 " yn
		case $yn in
			yes) break;;
			no) exit;;
			*) echo "Please type 'yes' or 'no'";;
		esac
	done
}

case $WHAT in
up)
	ensure_release
	export_variables
	interactive_confirmation "Are you sure you want to stand up ${NAME}?"
	move_kubeconfig
	kube_up
	clean_s3_buckets
	write_kubeconfig
	;;

down)
	ensure_release
	export_variables
	interactive_confirmation "Are you sure you want to tear down ${NAME}?"
	kube_down
	remove_kubeconfig
	;;

debug-clean-s3-buckets)
	clean_s3_buckets
	;;

*)
	echo "Unknown command"
	exit 1
	;;
esac
