#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if [ $# -ne 1 ]
then
	echo "usage: $(basename $0) <name>"
	exit 1
fi

NAME=$1
CLWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/${NAME}"

if [ ! -d ${CLWD} ]
then
	echo "${CLWD} is not a directory"
	exit 1
fi

kubectl --kubeconfig=${CLWD}/kubeconfig get nodes -o json | jq -r '.items[].status.addresses[] | select(.type == "ExternalIP").address'
