# This file is automatically generated by the rds script.
# Do not edit this file by hand.

users_db_password = "a59f8e66c75eceb"
app_mapper_db_password = "d2e5268c1ab252e"
minion_security_group_id = "sg-2a1c984e"
