# This file was created from a template.
# Probably do not edit this file directly.

variable "aws_access_key" {
}

variable "aws_secret_key" {
}

variable "aws_region" {
}

provider "aws" {
    access_key = "${var.aws_access_key}"
    secret_key = "${var.aws_secret_key}"
    region = "${var.aws_region}"
}

