aws_access_key = "AKIAJ3QEOZMGYRLSBKCA"
aws_secret_key = "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"
region = "eu-west-1"
rds_subnet_a_availability_zone = "eu-west-1a"
rds_subnet_b_availability_zone = "eu-west-1b"
rds_subnet_c_availability_zone = "eu-west-1c"
app_mapper_db_password = "b714735f9054"
users_db_password = "e2fa502c943a"
