#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if [ $# -ne 2 ]
then
	echo "usage: $(basename $0) up/down <name>"
	exit 1
fi

WHAT=$1
NAME=$2

function create_tf_file {
	cp rds.template ${NAME}/r53.tf
}

function delete_tf_file {
	rm -f ${NAME}/r53.tf
}

function terraform_apply {
	echo TODO
}

case $WHAT in
up)
	create_tf_file
	terraform_apply
	;;
down)
	delete_tf_file
	terraform_apply
	;;
*)
	echo "Unknown command"
	exit 1
	;;
esac
