#!/usr/bin/env bash

if [ $# -ne 2 ]
then
	echo "usage: $(basename $0) up/down <name>"
	exit 1
fi

WHAT=$1
NAME=$2

function create_tf_file {
	cp rds.template ${NAME}/rds.tf
}

function delete_tf_file {
	rm -f ${NAME}/rds.tf
}

function terraform_apply {
	local tempfile=$(mktemp)
	trap "rm -rf ${tempfile}" EXIT
	terraform plan -state=${NAME}.tfstate -var-file=${NAME}.tfvars -target=aws_db_instance.users_db -target=aws_db_instance.app_mapper_db -out=${tempfile}
	interactive_confirmation "Do you wish to proceed with the plan?"
	terraform apply -state=${NAME}.tfstate ${tempfile}
}

case $WHAT in
up)
	create_tf_file
	terraform_apply
	;;
down)
	delete_tf_file
	terraform_apply
	;;
*)
	echo "Unknown command"
	exit 1
	;;
esac
