#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if [ $# -ne 2 ]
then
	echo "usage: $(basename $0) <name>"
	exit 1
fi

NAME=$1

# hostname=$( cat ${NAME}.tfstate | jq -r .modules[0].resources.\"aws_db_instance.${dbname}\".primary.attributes.address )
# suffix=$(date | shasum | cut -c1-5)
# podname="rdsload-${suffix}"
# echo "Loading ${filename} to ${hostname}..."
# trap "kubectl stop pod --grace-period=1 ${podname}" EXIT
# cat ${filename} | kubectl run ${podname} --image=postgres --stdin --restart=Never --env="PGPASSWORD=${password}" --command -- psql -U postgres -h ${hostname}
