#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

function usage {
	echo "usage: $(basename $0) up/down <name>" 1>&2
	exit 1
}


if [ $# -ne 2 ]
then
	usage
fi

WHAT=$1
NAME=$2
CLWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/${NAME}"

if [ ! -d ${CLWD} ]
then
	echo "${CLWD} is not a directory"
	exit 1
fi

function create_tf_file {
	echo "Creating ${CLWD}/sqs.tf"
	cp sqs.template ${CLWD}/sqs.tf
}

function delete_tf_file {
	echo "Deleting ${CLWD}/sqs.tf"
	rm -f ${CLWD}/sqs.tf
}

function interactive_confirmation {
	while true
	do
		read -p "$1 " yn
		case $yn in
			yes) break;;
			no) exit;;
			*) echo "Please type 'yes' or 'no'";;
		esac
	done
}

TARGETS="
    -target=aws_iam_user.sqs_readwriter
    -target=aws_iam_access_key.sqs_readwriter_key
    -target=aws_iam_user_policy.sqs_readwriter_policy"

function terraform_destroy {
	(
		cd ${CLWD}
		terraform plan -destroy -state=tfstate -var-file=tfvars ${TARGETS}
		interactive_confirmation "Does this look right?"
		terraform destroy -state=tfstate -var-file=tfvars ${TARGETS}
	)
}

function terraform_apply {
	(
		cd ${CLWD}
		local tempfile=$(mktemp)
		trap "rm -rf ${tempfile}" EXIT
		terraform plan -state=tfstate -var-file=tfvars -out=${tempfile} ${TARGETS}
		interactive_confirmation "Do you wish to proceed with the plan?"
		terraform apply -state=tfstate ${tempfile}
	)
}

case $WHAT in
up)
	create_tf_file
	terraform_apply
	;;

down)
	terraform_destroy
	delete_tf_file
	;;

*)
	echo "Unknown command" 1>&2
	usage
	;;
esac
