apiVersion: v1
kind: ReplicationController
metadata:
  name: app-mapper
  labels:
    name: app-mapper
spec:
  replicas: 1
  selector:
    name: app-mapper
  template:
    metadata:
      labels:
        name: app-mapper
    spec:
      containers:
      - name: app-mapper
        image: quay.io/weaveworks/app-mapper
        args:
        # command = "/app-mapper"
        - -db-uri=postgres://postgres@app-mapper-db/app_mapper?sslmode=disable
        - -log-level=debug
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 80
