apiVersion: v1
kind: Service
metadata:
  name: frontend-mt
  labels:
    name: frontend-mt
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    name: frontend-mt
