apiVersion: v1
kind: Service
metadata:
  name: mailcatcher
  annotations:
    prometheus.io.scrape: "false"
spec:
  ports:
    - port: 587
      name: smtp
    - port: 80
      name: http
  selector:
    name: mailcatcher
