apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring
  labels:
    name: monitoring
spec:
  replicas: 1
  selector:
    name: monitoring
  template:
    metadata:
      labels:
        name: monitoring
    spec:
      containers:
      - name: prometheus
        image: quay.io/weaveworks/prometheus
        ports:
        - containerPort: 9090
      - name: grafana
        image: quay.io/weaveworks/grafana
        ports:
        - containerPort: 3000
      - name: gfdatasource
        image: quay.io/weaveworks/gfdatasource
      - name: loadgen
        image: quay.io/weaveworks/loadgen
      - name: alertmanager
        image: quay.io/weaveworks/alertmanager
        ports:
        - containerPort: 9093
