apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring
  labels:
    name: monitoring
spec:
  replicas: 1
  selector:
    name: monitoring
  template:
    metadata:
      labels:
        name: monitoring
    spec:
      containers:
      - name: monitoring
        image: quay.io/weaveworks/monitoring
        command:
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 3000
        - containerPort: 9090
