apiVersion: v1
kind: ReplicationController
metadata:
  name: s3
spec:
  replicas: 1
  selector:
    name: s3
  template:
    metadata:
      labels:
        name: s3
    spec:
      containers:
      - name: s3
        image: lphoward/fake-s3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4569
