apiVersion: v1
kind: ReplicationController
metadata:
  name: ui-server
spec:
  replicas: 1
  selector:
    name: ui-server
  template:
    metadata:
      labels:
        name: ui-server
    spec:
      containers:
      - name: ui-server
        image: quay.io/weaveworks/ui-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
