apiVersion: v1
kind: ReplicationController
metadata:
  namespace: monitoring
  name: monitoring-20160630
spec:
  replicas: 1
  selector:
    name: monitoring
    version: '20160630'
  template:
    metadata:
      labels:
        name: monitoring
        version: '20160630'
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name: prometheus
        image: quay.io/weaveworks/prometheus:master-e8783c3
        args:
        - -alertmanager.url=http://localhost:9093/admin/alertmanager/
        ports:
        - containerPort: 9090
      - name: loadgen
        image: quay.io/weaveworks/loadgen:6d14ba2
      - name: alertmanager
        image: quay.io/weaveworks/alertmanager:master-e8783c3
        args:
        - -config.file=/etc/alertmanager/alertmanager-prod.yml
        - -web.external-url=http://cloud.weave.works/admin/alertmanager/
        ports:
        - containerPort: 9093
