global:
  smtp_smarthost: 'email-smtp.us-east-1.amazonaws.com:25'
  smtp_from: 'noreply@weave.works'

templates:
- '/etc/alertmanager/*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  continue: true

  routes:
  - match:
    receiver: service-alerts-dev

receivers:
- name: 'service-alerts-dev'
  email_configs:
  - to: 'service-alerts-dev@weave.works'
