apiVersion: v1
kind: Service
metadata:
  name: frontend-transition
  labels:
    name: frontend-transition
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    name: frontend
  type: LoadBalancer
