apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  replicas: 2
  selector:
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name: frontend
        image: quay.io/weaveworks/frontend:2bb19e4
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
