apiVersion: v1
kind: Service
metadata:
  name: monitoring
spec:
  ports:
    - name: prometheus
      port: 9090
    - name: alertmanager
      port: 9093
    - name: grafana
      port: 3000
  selector:
    name: monitoring
