#!/bin/bash

echo starting loadgen...
trap "{ echo stopping loadgen; exit 0; }" INT TERM

http() {
	METHOD=$1
	URL=$2
	curl -Ss -X$METHOD $URL >/dev/null 2>&1
}

while true
do
	for url in http://app-mapper/loadgen http://users/loadgen
	do
		http GET $url
	done
	sleep 1
done

