global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'kubernetes-services'
  kubernetes_sd_configs:
  - masters:
    - 'https://kubernetes.default.svc'
    in_cluster: true
