#!/bin/bash

cd /prometheus
exec ./prometheus \
	-config.file=/etc/prometheus/prometheus.yml \
	-storage.local.path=/prometheus/data \
	-web.console.libraries=/etc/prometheus/console_libraries \
	-web.console.templates=/etc/prometheus/consoles \
	-web.listen-address=:9090

