apiVersion: v1
kind: ReplicationController
metadata:
  name: users
  labels:
    name: users
spec:
  replicas: 1
  selector:
    name: users
  template:
    metadata:
      labels:
        name: users
    spec:
      containers:
      - name: users
        image: quay.io/weaveworks/users
        args:
        # command = "/users"
        - -session-secret=3919365780a79e0658fde4d03e6945a080031ec077b88975898f698c0d298395
        - -email-uri=smtp://mailcatcher:587
        - -database-uri=postgres://postgres@users-db/users?sslmode=disable
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 80
