apiVersion: v1
kind: Service

metadata:
  labels:
    app: helloworld
  name: helloworld

spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: helloworld  # find any pod with labels "app=helloworld"
  type: LoadBalancer # Use the platform load balancer
