apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: scope-probe
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: scope-probe
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name:  scope-probe
        image: weaveworks/scope
        imagePullPolicy: IfNotPresent
        env:
        - name: CHECKPOINT_DISABLE
          value: "true"
        args:
        - --no-app
        - --probe.docker=true
        - --probe.kubernetes=true
        - --probe.processes=false
        # Workaround for https://github.com/kubernetes/kubernetes/issues/17406
        - --probe.resolver=$(KUBE_DNS_SERVICE_HOST):$(KUBE_DNS_SERVICE_PORT)
        - scope.kube-system.svc.cluster.local:80
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 50m
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
