apiVersion: v1
kind: Service
metadata:
  name: launch-generator
  annotations:
    prometheus.io.scrape: "false"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
  selector:
    name: launch-generator
