apiVersion: v1
kind: Service
metadata:
  name: memcached
  annotations:
    prometheus.io.port: "9150"
spec:
  ports:
    - name: clients
      port: 11211
    - name: prom
      port: 9150
  selector:
    name: memcached
