apiVersion: v1
kind: ReplicationController
metadata:
  name: pipe
spec:
  replicas: 1
  selector:
    name: pipe
  template:
    metadata:
      labels:
        name: pipe
    spec:
      containers:
      - name: pipe
        image: weaveworks/scope
        imagePullPolicy: IfNotPresent
        args:
        - --no-probe
        - --weave=false
        - --app.log.http=true
        - --app.http.address=:80
        - --app.userid.header=X-Scope-OrgID
        - --app.pipe.router=consul://consul.default.svc.cluster.local:8500/pipes/
        - --app.consul.inf=eth0
        env:
        - name: CHECKPOINT_DISABLE
          value: "1"
        - name: SCOPE_HOSTNAME
          value: "service"
        ports:
        - containerPort: 80
