[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.3.0"

[[override]]
  name = "github.com/weaveworks/common"
  branch = "master"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.0.0"
