apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  replicas: 1
  selector:
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name: frontend
        image: quay.io/weaveworks/frontend:2ba2f58
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
