apiVersion: v1
kind: ReplicationController

metadata: # of this rc
  labels:
    app: helloworld # These labels are useful for selecting this rc.
    track: stable   # They're consumed by things that select rcs, e.g. services.
  name: helloworld-1.0.0

spec:
  replicas: 1
  selector:         # This rc will select pods matching...
    app: helloworld #  these
    track: stable   #   label
    version: 1.0.0  #    dimensions

  template:
    metadata:
      labels:           # This rc will create pods and give them...
        app: helloworld #  these
        track: stable   #   label
        version: 1.0.0  #    dimensions
    spec:
      containers:
        - image: docker.io/peterbourgon/helloworld:1.0.0
          name: helloworld
          ports:
            - containerPort: 80 # Our application binds to this port inside the container
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/"
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 3

