apiVersion: v1
kind: ReplicationController
metadata:
  namespace: aws
  name: users-db
spec:
  replicas: 1
  selector:
    name: users-db
  template:
    metadata:
      labels:
        name: users-db
    spec:
      containers:
      - name: users-db
        image: weaveworks/users-db
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
