users:
  extends:
    file: docker-compose.yml
    service: users
  command: -session-secret 3919365780a79e0658fde4d03e6945a080031ec077b88975898f698c0d298395 -email-uri=smtp://AKIAJC77KJCIV4HRCM2Q:AqliFmKAFLPagTQkd6FuoZHQDolVU195DorateSEKsTO@email-smtp.us-east-1.amazonaws.com:587 -database-uri=postgres://postgres:bUSiJs6GaP1KuvQMi-75snl8@users-db.crwiyf99ij1c.us-east-1.rds.amazonaws.com/users?sslmode=disable
