apiVersion: v1
kind: ReplicationController
metadata:
  namespace: monitoring
  name: monitoring-20160630b
spec:
  replicas: 1
  selector:
    name: monitoring
    version: '20160630b'
  template:
    metadata:
      labels:
        name: monitoring
        version: '20160630b'
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name: prometheus
        image: quay.io/weaveworks/prometheus:fix-dev-alerts-97c6dc0
        args:
        - -alertmanager.url=http://localhost:9093/admin/alertmanager/
        ports:
        - containerPort: 9090
      - name: loadgen
        image: quay.io/weaveworks/loadgen:6d14ba2
      - name: alertmanager
        image: quay.io/weaveworks/alertmanager:fix-dev-alerts-312ef59
        args:
        - -config.file=/etc/alertmanager/alertmanager-dev.yml
        - -web.external-url=http://frontend.dev.weave.works/admin/alertmanager/
        ports:
        - containerPort: 9093
