apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: monitoring
spec:
  ports:
  - port: 9093
    name: alertmanager
  - port: 9090
    name: prometheus
  - port: 3000
    name: grafana
  selector:
    name: monitoring
