apiVersion: v1
kind: ReplicationController
metadata:
  namespace: monitoring
  name: monitoring-20160630b
spec:
  replicas: 1
  selector:
    name: monitoring
    version: '20160630b'
  template:
    metadata:
      labels:
        name: monitoring
        version: '20160630b'
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name: prometheus
        image: quay.io/weaveworks/prometheus:HEAD-b39ed30
        ports:
        - containerPort: 9090
      - name: loadgen
        image: quay.io/weaveworks/loadgen:6d14ba2
      - name: alertmanager
        image: quay.io/weaveworks/alertmanager:fix-dev-alerts-312ef59
        args:
        - -config.file=/etc/alertmanager/alertmanager-dev.yml
        env:
        - name: SMTP_AUTH_USERNAME      # See alertmanager's config file
          value: 'AKIAIV2MAR7JNRV6V2CA' # ses-smtp-user.20160108-111651.alertmanager
        - name: SMTP_AUTH_PASSWORD
          value: 'Av+GtaUk/JcR4239ke+iSi3dPAwB8yc66wnuRUZtLoa3'
        ports:
        - containerPort: 9093
