version: '2'
services:

  config-db:
   image: "postgres:10.6"
   expose:
    - "5432"
   environment:
    - POSTGRES_DB=notifications

  sqslocal:
    image: "pakohan/elasticmq"
    expose:
     - "9324"

  nats:
    image: "nats:0.8.0"
    expose:
    - "4222"
    - "8222"
    - "6222"

  mailcatcher:
    image: schickling/mailcatcher
    expose:
    - "587"
    command: |
      mailcatcher -f --ip=0.0.0.0 --smtp-port=587 --http-port=80

  eventmanager:
    depends_on:
      - sqslocal
      - config-db
    image: weaveworks/notification-eventmanager
    command: |
      -log.level=info
      -sqsURL=sqs://user:password@sqslocal.e2e_default:9324/events
      -usersServiceURL=mock
      -database.uri=postgres://postgres@config-db/notifications?sslmode=disable
      -database.migrations=/migrations
      -eventtypes=/mnt/eventtypes.json
    volumes:
      - ./eventtypes.json:/mnt/eventtypes.json

  sender:
    depends_on:
      - sqslocal
      - nats
      - mailcatcher
    image: weaveworks/notification-sender
    command: |
      -log.level=info
      -nats=nats://nats:4222 
      -sqsURL=sqs://user:password@sqslocal.e2e_default:9324/events
      -emailURI=smtp://mailcatcher:587

  tester:
    depends_on:
      - eventmanager
      - sender
    image: weaveworks/build
    volumes:
      - ../..:/go/src/github.com/weaveworks/service
    working_dir: /go/src/github.com/weaveworks/service/notification-eventmanager/e2e
    entrypoint: /bin/bash
    command: -c "go test -v"
