FROM quay.io/weaveworks/build
MAINTAINER Weaveworks Inc <help@weave.works>
WORKDIR /
COPY . /go/src/github.com/weaveworks/service
WORKDIR /go/src/github.com/weaveworks/service/notification-eventmanager/test
ENTRYPOINT /bin/bash -c "go test -v"
